name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Setup Julia
          uses: julia-actions/setup-julia@latest
          with:
            version: '1.8'  # Use the version you prefer
    
        - name: Run tests
          uses: julia-actions/julia-runtest@latest